### ISSUE TITLE
Mutation annotations

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/dashboard-components#732]
To address https://github.com/GenSpectrum/dashboards/issues/478, @anna-parker and I came up with the following approach:

We have various places where mutations are printed: in particular, we have long lists of mutations in the mutations, mutations-over-time and mutation-comparison components. For many users, it is unclear which mutations are of interest; therefore, the maintainer of a dashboard should be able to provide annotations.

Annotated mutations should have a symbol next to it like a `*` or a `+`. If the user click on the symbol, a popup should show up with further details.

The annotations are provided in a YAML like this:

```
- name: Anti viral resistance
  description: some text that may include HTML (or markdown?)
  symbol: *
  nucleotideMutations:
    - 35T
    - 234G
  aminoAcidMutations:
   - S:501Y
```

The annotations should be provided to `<gs-app>` and impact the display of mutations in the different components.
